name: Publish Code
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore testzk/testzk.csproj
        
      - name: Build
        run: dotnet build testzk/testzk.csproj --configuration Release --no-restore
        
  publish:
    runs-on: ubuntu-latest
    needs: build 
    steps:            
      - name: List directory contents
        run: ls -R  # Check the file structure

      - name: Publish
        run: dotnet publish testzk/testzk.csproj --configuration Release --no-build --output ./publish 
        
      - name: List Published Files
        run: ls ./publish  # Verify the contents of the publish directory
               
      - name: Upload publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: ./publish  
        
  deploy:
    runs-on: windows-latest
    needs: publish      
    steps:
      - name: Download Publish Artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: ./myartifact.zip  # Specify the output path for the artifact

      - name: Publish to on-prem VM
        run: |
          net use D: \\10.100.66.18\artifacts /user:${{ secrets.IIS_SERVER_USER }} ${{ secrets.IIS_SERVER_PASSWORD }}
          
          # Check if the artifact exists
          if exist D:\myartifact.zip (
            echo "Artifact exists"
          ) else (
            echo "Artifact does not exist"
            exit 1
          )
      
          # Extract the Artifact
          powershell -command "Expand-Archive -Path 'D:\myartifact.zip' -DestinationPath 'D:\artifacts\'"
      
          # Copy the artifact to the on-prem VM
          xcopy /Y /I D:\artifacts\* D:\artifacts
      
          # Clean up by deleting the mapped drive
          net use D: /delete
