name: Publish Code
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore testzk/testzk.csproj
        
      - name: Build
        run: dotnet build testzk/testzk.csproj --configuration Release --no-restore
                 
      - name: Publish
        run: dotnet publish testzk/testzk.csproj  --configuration Release --no-build --output ./publish 
        
      - name: List directory contents
        run: ls -R ./publish  # Optional: List files in the publish directory for debugging

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Copy files to IIS
        uses: appleboy/scp-action@master
        with:
          website-name: 'MyWebsite'
          msdeploy-service-url: "https://rpasocldev.dalmiabharat.com/TestProject/"
          msdeploy-username: ${{ secrets.IIS_SERVER_USER }}
          msdeploy-password: ${{ secrets.IIS_SERVER_PASSWORD }}
          source-path: "./publish/*"
       
      - name: Restart IIS
        run: |
          Invoke-Expression -Command "Restart-WebAppPool -Name 'DefaultAppPool'" # Change app pool name
        shell: pwsh
